# Generated by Django 2.0.4 on 2018-04-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments_num',
            field=models.IntegerField(default=0),
        ),
    ]
